### ISSUE TITLE
TIAtracker 100% CPU usage (QThreat) - no track loaded

### ISSUE THREAD

**Issue by alexmyczko** [chunkypixel/batariBasic-TIATracker#1]
A user reports this problem, maybe you know something?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1025675

**Comment by chunkypixel** [comment]
Hi there! I think this will relate to the creator/editor program rather than this repository which provides examples of using TIATracker music files on the 2600 (batariBasic) or 7800 (7800basic).

**Comment by alexmyczko** [comment]
You are so right the project is not on github, will correct.
